### ISSUE TITLE
Errors in pd

### ISSUE THREAD

**Issue by Xender** [MoserMichael/cstuff#3]
Crash at module import, the hard way.

```
Traceback (most recent call last):
[...]
  File "[...]", line 5, in <module>
    import pd
  File "[...]/venv/lib/python3.5/site-packages/pd/__init__.py", line 3, in <module>
    from pd.pdd import print_stack_ex, print_exception_ex, die, die2
  File "[...]/venv/lib/python3.5/site-packages/pd/pdd.py", line 18
    return value
               ^
TabError: inconsistent use of tabs and spaces in indentation
```

Mixing tabs and spaces in Python is forbidden.

Tab doesn't have 8 spaces. It doesn't also have 4, 2, or any fixed number of spaces.
The whole idea is that user can choose whatever tab size they like in their text editor.

So please, don't use "indendation levels" of [4 spaces, 1 tab, 1 tab 4 spaces, 2 tabs, 2 tabs 4 spaces]...
It's hell in any programming language, and also forbidden in Python.

And also please, test if your module even imports before submitting to PyPI.

**Comment by cgi1** [comment]
Still an issue.. Not usable.
